### ISSUE TITLE
Consider using the BCL Lazy type as the base of LazyList.

### ISSUE THREAD

**Issue by teo-tsirpanis** [fsprojects/FSharpx.Collections#113]
### Description

As it's currently implemented, `LazyList` uses mutable members and lock constructs to implement the thread-safe laziness. Why not use the `Lazy<T>` type the framework already provides? It would make implementation and testing easier, remove the mutable members on its interface (which are visible by anyone BTW; somebody could completely change it easily), and `LazyList` will be built upon a more sure and standard construct.

**Comment by jackfoxy** [comment]
I'm sure at one point there was a completely different implementation of LazyList, but you would have to do some archeology to find it. The git history prior to breaking out this repo from the old FSharpx repo was lost due to the way the break-out was done. 

I think the older version also included equality, which may be the problem with this issue:
https://github.com/fsprojects/FSharpx.Collections/issues/114

There is a signature file over this collection, and I haven't used this collection in a long time, other than converting the tests to Expecto. @teo-tsirpanis can you provide an example of the exposed mutable member?

You're certainly welcome to submit a PR that passes all the tests, provably does not negatively impact performance, and perhaps addresses issue 114.

**Comment by teo-tsirpanis** [comment]
Oh, I forgot about the signature file. 😲😛 Still, the conversion would make `LazyList`'s _implementation_ simpler and safer.

As for equality, I think that the `LazyList` is rightfully not equatable and comparable. The concept of equality (or more confusingly comparison) on a potentially infinite list does not make sense.

I will make a PR if I have time. And I will also see #114.

**Comment by jackfoxy** [comment]
I tend to agree with you, although in terms of equality and https://github.com/fsprojects/FSharpx.Collections/issues/114 perhaps ````LazyList```` could use a ````compareWith```` function, like ````Seq````, which can also be infinite.

It's still a mystery why some of these experimental tests succeeded under NUnit, but not Expecto.

**Comment by teo-tsirpanis** [comment]
> LazyList could use a compareWith function, like Seq, which can also be infinite.

That's a better option. Casting to `seq` is a code smell IMHO.

**Comment by jackfoxy** [comment]
@teo-tsirpanis  please consider a PR of your lazy list to Collections.Experimental. https://github.com/fsprojects/FSharpx.Collections/pull/121#issuecomment-402532492
