### ISSUE TITLE
Fable compatibility 

### ISSUE THREAD

**Issue by OnurGumus** [fsprojects/FSharpx.Collections#156]
Title says all.

**Comment by njlr** [comment]
https://github.com/fsprojects/FSharpx.Collections/pull/160

**Comment by jackfoxy** [comment]
@OnurGumus  the PR has been merged into master. 
Does this meet your Fable compatibility requirements?

**Comment by OnurGumus** [comment]
wonderful! thanks.

**Comment by njlr** [comment]
Not sure how you want to manage issues etc, but quite a few things are still missing on the Fable side. Some are due to limitations of Fable (e.g. some stuff around generics and threads). I also didn't port the "experimental" module.

Perhaps we should open issues for each of these? 

e.g. "Port PersistentVector to Fable"

**Comment by njlr** [comment]
We should also add the Fable tests to the CI process to make sure they don't break over time.

**Comment by jackfoxy** [comment]
@njlr  
Since you have the better understanding, I suggest you add issues for
1) port experimental module (this should not hold up a new release)
2) add Fable tests to CI, most importantly that it run in Appveyor. That is the only CI that currently reliably runs.
3) whatever else should be tracked (use your judgement)

Some collections, like PersistentVector, are probably too hard to port to Fable.

I'll also rely on your judgement as to when this is ready for a new release. We could make a beta release for the interim.
