### ISSUE TITLE
PCL Version

### ISSUE THREAD

**Issue by bordoley** [fsprojects/FSharpx.Collections#23]
Have you considered releasing FSharpX collections as a PCL library? It appears that several of the implementations utilize APIs not in the 259 PCL profile (threading APIs for instance), but a bait and switch approach could be used to support the most common platform (net45, android, ios and win phone).

**Comment by laygr** [comment]
I would appreciate it a lot. Currently, I'm manually including the files that I'm allowed to use for iOS/Android in the project I'm working on.

**Comment by matthid** [comment]
Actually the PCL version was already there in the past [here](https://github.com/fsprojects/FSharpx.Collections/commit/b143bddfdb0530de7657d77fac73da6b5ef51886), but was removed [there](https://github.com/fsprojects/FSharpx.Collections/commit/955ae2bfea562d15dbf87b236d35b9d91a0ca5bd) 

@forki Can we not update the build.fsx file because it will be reset on a projectscaffold update?

**Comment by bordoley** [comment]
FWIW providing a PCL version of this project is likely non-trivial. Many of the underlying implementations such as PersistentVector depend upon the presence of threading primitives not available in the PCL profile, therefore you would need to build this package using the nuget bait and switch technique.

**Comment by jackfoxy** [comment]
https://github.com/fsprojects/FSharpx.Collections/issues/77 is actively being worked on. Will netstandard support sufficiently satisfy this issue? If so we we should close this. @bordoley

**Comment by jackfoxy** [comment]
Closing. If netstandard does not meet your needs, provide a repo demoing the problem.
