### ISSUE TITLE
Do we want ResizeArray to go to experimental?

### ISSUE THREAD

**Issue by forki** [fsprojects/FSharpx.Collections#8]
// cc @jackfoxy

**Comment by jackfoxy** [comment]
/// Generic operations on the type System.Collections.Generic.List, which is called ResizeArray in the F# libraries.

made clear in the intellisense

Otherwise covered by https://github.com/fsprojects/FSharpx.Collections/issues/2

As for moving to experimental, I think after 4.5 years this is grandfathered.
